AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  restaurantsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: restaurants
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  MyV2PageDevGetIndex:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/get-index.handler
      Runtime: nodejs10.x
      CodeUri: /Users/luis/serverless/production-ready/v2/.serverless/my-v2-page.zip
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'dynamodb:scan'
              Resource: >-
                arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants
            - Effect: Allow
              Action: 'execute-api:Invoke'
              Resource: >-
                arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants
      Environment:
        Variables:
          restaurants_api: >-
            https://1lonxdayp9.execute-api.us-east-1.amazonaws.com/dev/restaurants
          cognito_user_pool_id: us-east-1_d4q7yZEzT
          cognito_client_id: 6nqh2fllo7u3li0ccetlg2o1sm
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: MyV2Page
  MyV2Page:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyV2PageDevGetIndex.Arn}/invocations
              responses: {}
          /restaurants/:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyV2PageDevGetRestaurants.Arn}/invocations
              responses: {}
              security:
                - Aws_iam: []
          /restaurants/search:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyV2PageDevSearchRestaurants.Arn}/invocations
              responses: {}
        securityDefinitions:
          Aws_iam:
            type: apiKey
            name: Aws_iam
            in: header
            x-amazon-apigateway-authtype: oauth2
            x-amazon-apigateway-authorizer:
              type: token
              authorizerUri:
                'Fn::Sub': >-
                  arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Aws_iam.Arn}/invocations
              identityValidationExpression: '^x-[a-z]+'
              authorizerResultTtlInSeconds: 60
  MyV2PageDevGetIndexLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - MyV2PageDevGetIndex
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: MyV2PageDevGetIndex
      Principal: apigateway.amazonaws.com
  MyV2PageDevGetRestaurants:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/get-restaurants.handler
      Runtime: nodejs10.x
      CodeUri: /Users/luis/serverless/production-ready/v2/.serverless/my-v2-page.zip
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'dynamodb:scan'
              Resource: >-
                arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants
            - Effect: Allow
              Action: 'execute-api:Invoke'
              Resource: >-
                arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants
      Environment:
        Variables:
          restaurants_table: restaurants
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /restaurants/
            Method: get
            RestApiId:
              Ref: MyV2Page
  Aws_iamResourcePolicy:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - Aws_iam
          - Arn
      Principal: apigateway.amazonaws.com
      SourceAccount:
        Ref: 'AWS::AccountId'
  MyV2PageDevGetRestaurantsLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - MyV2PageDevGetRestaurants
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: MyV2PageDevGetRestaurants
      Principal: apigateway.amazonaws.com
  MyV2PageDevSearchRestaurants:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/search-restaurants.handler
      Runtime: nodejs10.x
      CodeUri: /Users/luis/serverless/production-ready/v2/.serverless/my-v2-page.zip
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'dynamodb:scan'
              Resource: >-
                arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants
            - Effect: Allow
              Action: 'execute-api:Invoke'
              Resource: >-
                arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants
      Environment:
        Variables:
          restaurants_table: restaurants
      Events:
        Event1:
          Type: Api
          Properties:
            Path: /restaurants/search
            Method: post
            RestApiId:
              Ref: MyV2Page
  MyV2PageDevSearchRestaurantsLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - MyV2PageDevSearchRestaurants
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: MyV2PageDevSearchRestaurants
      Principal: apigateway.amazonaws.com
